[package]
name = "bit10_exchange"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "bit10_exchange"

[dependencies]
anchor-lang = "0.31.0"
anchor-spl = { version = "0.31.0", features = ["token", "token_2022", "associated_token", "idl-build"] }

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]  # ← add anchor-spl here

[patch.crates-io]
# Force the entire tree to use one consistent spl-token-2022 version
spl-token-2022 = { version = "6.0.0" }
